### ISSUE TITLE
File access: investigate how files are stored, organized and shared within the client

### ISSUE THREAD

**Issue by tagtuna** [tagbase/tagbase-server#170]
Jesus responded that "At ICCAT we have Microsoft SharePoint officially. We have an iccat-tagging folder." It remains to be vetted whether this organization is optimal or alternate structures should be set up. I think curl might be able to get a file cloud-stored on SharePoint - see here https://www.c-sharpcorner.com/article/download-sharepoint-online-files-using-mac-curl-command/

But it is unclear if such an access method remains valid or may break down if Microsoft decides to update whatever policies on their end. Will ask Jesus to try the above script and curl the file locally before we pursue any further

**Comment by tagtuna** [comment]
SharePoint also has some documentation on their REST API - https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest

**Comment by lewismc** [comment]
@tagtuna is the goal here to pull in files from Sharepoint? If we have an authentication mechanism then we may be able to use the existing `GET /ingest` function to retrieve over HTTPS... can you please clarify? Thanks

**Comment by tagtuna** [comment]
Sharepoint is their official services, but they are using multiple services to store/ share files. I suggest we spend some time after the mini-meeting with Jesus to see if Sharepoint is straightforward or not. I would imagine, if outside partners want to share a file with ICCAT, they will gain access (invite) to upload to a file service like Sharepoint or Google Drive, rather than the more try and trusted ways via email/ FTP

**Comment by tagtuna** [comment]
MobaXterm drag-and-drop transfer of files are ok with them for now
