### ISSUE TITLE
Augment submission table with ingestion task context and status

### ISSUE THREAD

**Issue by lewismc** [tagbase/tagbase-server#173]
At yesterdays team meeting we determined that it would be advantageous to capture more information about tag submissions. Specifically

**Lifecycle Stages**
- `anomaly_report` - character varying(30) with Foreign key link to `anomaly` table which needs to be created
- `migration_duration` - timestamp(6) with time zone NOT NULL
- `start` - timestamp(6) with time zone NOT NULL
- `status` - ENUM('`FAILED`', '`FINISHED`', '`KILLED`', '`RUNNING`') NOT NULL
- `total_runtime` - integer

**Statuses**
- `FAILED`: runtime anomaly resulted in erroneous ingestion execution
- `FINISHED`: successful ingestion
- `KILLED`: manually killed ingestion job, for example this could be executed by an authorized user to kill/stop ingestion of huge payloads which were executed perhaps by mistake
- `RUNNING`: job currently executing

This additional context fore the submissions table would mean a minor change to the _rollback/transaction_ model we have in place right now where no submission is written unless the entire file (including data migration TRIGGER) is successfully ingested. Instead we would simply have the connection `commit` after the **lifecycle stages** stated above.

@tagtuna thoughts?

**Comment by tagtuna** [comment]
`start` & `migration_duration` I suggest that they can be modified as `time_start` and `time_status`, the latter being a more generalized way to capture the timestamp for a given status, say for `FINISHED` it would be the time when data migration is completed

**Comment by lewismc** [comment]
Hi @tagtuna OK thanks. Should I elaborate on `RUNNING` to include a `PREMIGRATION` --> `MIGRATION` --> `POSTMIGRATION` --> `FINISHED`? We would also have time duration's for those phases i.e., `time_premigration`, `time_migration`, `time_postmigration`?

**Comment by tagtuna** [comment]
Yes it will be helpful to elaborate on the `running` cycle. I made the suggestion based on the thinking that at a given time, there is only one "latest" status, and the timestamp captured would reflect that. With `time_` + statuses I am guessing we are tracking every status, a level of details that may not be needed - since an average end user is mostly concerned about the latest info.

**Comment by lewismc** [comment]
OK so how about we
* create following ENUM's `FAILED`, `FINISHED`, `KILLED`, `MIGRATION`, `PREMIGRATION` and `POSTMIGRATION`
* replace `start` with `time_start`

I am still not sure about the migration information we wish to persist. The reason I suggested that we explicitly capture migration duration was that, currently, this takes the longest (however I intent to reduce migration runtime duration...).

**Comment by tagtuna** [comment]
I agree migration duration needs tracking, so how about we have `time_migration` on top of `time_start` and forget about `time_status`?

**Comment by lewismc** [comment]
Yes. Perfect. New `submission` table structure 
```
CREATE TYPE status_enum AS ENUM ('FAILED', 'FINISHED', 'KILLED', 'MIGRATION', 'POSTMIGRATION', 'PREMIGRATION');

CREATE TABLE submission (
    submission_id integer NOT NULL,
    tag_id integer NOT NULL,
    date_time timestamp(6) with time zone DEFAULT now() NOT NULL,
    filename text NOT NULL,
    version character varying(50),
    notes text
    time_migration - integer or interval representing seconds
    time_start - timestamp(6) with time zone NOT NULL
    status - status_enum NOT NULL
    time_total - integer or interval representing seconds
);
```

Anomaly table structure
```
CREATE TABLE anomaly (
    submission_id integer NOT NULL,
    tag_id integer NOT NULL,
    type character varying(30) NOT NULL,
    anomaly text NOT NULL
);

--
-- Name: anomaly anomaly_submission_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY anomaly
    ADD CONSTRAINT anomaly_submission_fkey FOREIGN KEY (submission_id, tag_id) REFERENCES submission(submission_id, tag_id);
```

**Comment by lewismc** [comment]
Superseded by #174
