### ISSUE TITLE
Implement DELETE admin tasks for tags and submissions

### ISSUE THREAD

**Issue by lewismc** [tagbase/tagbase-server#180]
The OpenAPI spec should be extended to permit 

* `DELETE /tags` - delete all tags, submissions and events
* `DELETE /tags/{tag_id}` - delete an individual tag, all associated submissions and events
* `DELETE /tags/{tag_id}/subs/{sub_id}` - delete an individual submission and associated events

Eventually once we implement events we can expand to the following...
* `DELETE /events` - delete all events for all tags and submissions
* `DELETE /events/{event_id}` - delete an individual event

**Comment by lewismc** [comment]
This should most likely be implemented after tagbase has been secured e.g. #27

**Comment by vtsontos** [comment]
I would recommend creating a stored procedure in tagbase that would cycle through and delete records for a specified Tag_ID.
This procedure then could either be invoked by the Tagbase DBA in postgres itself or via an API call that would be implemented leveraging that stored procedure.  I think this approach generally provides greater flexibility and allows quicker implementation and testing.

**Comment by lewismc** [comment]
Sample REST API design at https://github.com/tagbase/tagbase-server/pull/228
