### ISSUE TITLE
Implement DELETE stored procedures

### ISSUE THREAD

**Issue by lewismc** [tagbase/tagbase-server#235]
Should happen post #180 
It is preferred that any DELETE operations can also be executed in the absence of the SwaggerUI test client. This has the benefit of enabling a PG DB administrator to go into and execute the delete procedures in an ad-hoc fashion without the need of using the REST API.
We should refactor [tagbase_schema.sql](https://github.com/tagbase/tagbase-server/blob/main/services/postgis/tagbase_schema.sql) to add the stored procedures. We can then leverage them in [tags_controller.py](https://github.com/tagbase/tagbase-server/blob/main/tagbase_server/tagbase_server/controllers/tags_controller.py).

**Comment by renato2099** [comment]
The PR using stored-procedures for the delete operations is https://github.com/tagbase/tagbase-server/pull/261
